import{a as d,S as m,i as p}from"./assets/vendor-BSTwZ_tR.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const y="https://corsproxy.io/?url=",h="https://pixabay.com/api",g="52704159-1137319808f91d343a45c96fe",b="photo",L="horizontal",w=!0,$={method:"GET",headers:{Accept:"application/json","Content-Type":"application/json"}};function v(s){const o=`${h}/?key=${g}&q=${s}&image_type=${b}&orientation=${L}&safesearch=${w}`;return d(`${y}${o}`,$).then(e=>{if(!e.data)throw new Error(`HTTP error! Status: ${e.status}`);return e.data}).catch(e=>{console.log("Помилка запиту:",e)})}const n=document.querySelector("ul.gallery"),f=document.querySelector(".loader"),q=new m(".gallery li a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",nav:!0,captionDelay:250});function S(s){const o=s.map(e=>`<li class="gallery-item">
                <a class="gallery-link" href="${e.largeImageURL}">
                  <img class="gallery-image" src="${e.webformatURL}" width='100px' alt="${e.tags.split(",").slice(0,3).join(",")}">
                  <ul class="image-params">
                    <li><b>Likes</b>:<br> ${e.likes}</li>
                    <li><b>Views</b>:<br> ${e.views}</li>
                    <li><b>Comments</b>:<br> ${e.comments}</li>
                    <li><b>Downloads</b>:<br> ${e.downloads}</li>
                  </ul>
                </a>
              </li>`).join("");n.insertAdjacentHTML("beforeend",o),q.refresh()}function T(){n.innerHTML=""}function x(){n.classList.remove("is-shown"),f.classList.add("is-shown")}function l(){f.classList.remove("is-shown"),n.classList.add("is-shown")}const a=document.querySelector('[name="search-text"]'),P=document.querySelector("button"),E="Sorry, there are no images matching your search query. Please try again!",O="Please enter your search query image";function u(s){p.show({message:s,messageColor:"#ffffff",backgroundColor:"#fe5549",progressBar:!1,position:"center"})}P.addEventListener("click",s=>{if(s.preventDefault(),!a.value||a.value.trim()===""){a.value="",u(O);return}T(),x(),v(a.value).then(o=>{console.log(o),!o.hits||o.hits.length===0?(u(E),l()):(l(),S(o.hits),a.value="")}).catch(o=>console.log(o))});
//# sourceMappingURL=index.js.map
