import{a as m,S as d,i as p}from"./assets/vendor-BSTwZ_tR.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();let u="https://cors-anywhere.herokuapp.com/";u="https://corsproxy.io/?";const y="https://pixabay.com/api",h="52704159-1137319808f91d343a45c96fe",g="photo",b="horizontal",w=!0,L={method:"GET",headers:{Accept:"application/json","Content-Type":"application/json","X-Custom-Header":"custom value",mode:"no-cors"}};function $(s){return m(u+`${y}/?key=${h}&q=${s}&image_type=${g}&orientation=${b}&safesearch=${w}`,L).then(e=>{if(!e.data)throw new Error(`HTTP error! Status: ${e.status}`);return e.data}).catch(e=>{console.log("Помилка запиту:",e)})}const a=document.querySelector("ul.gallery"),f=document.querySelector(".loader");function v(s){const e=s.map(r=>`<li class="gallery-item">
                <a class="gallery-link" href="${r.largeImageURL}">
                  <img class="gallery-image" src="${r.webformatURL}" width='100px' alt="${r.tags.split(",").slice(0,3)}">
                  <ul class="image-params">
                    <li><b>Likes</b>:<br> ${r.likes}</li>
                    <li><b>Views</b>:<br> ${r.views}</li>
                    <li><b>Comments</b>:<br> ${r.comments}</li>
                    <li><b>Downloads</b>:<br> ${r.downloads}</li>
                  </ul>
                </a>
              </li>`).join("");a.insertAdjacentHTML("afterbegin",e),new d(".gallery li a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",nav:!0,captionDelay:250}).refresh()}function S(){a.innerHTML=""}function q(){a.classList.remove("is-shown"),f.classList.add("is-shown"),console.log("show")}function T(){f.classList.remove("is-shown"),a.classList.add("is-shown"),console.log("hide")}const c=document.querySelector('[name="search-text"]'),x=document.querySelector("button"),P="Sorry, there are no images matching your search query. Please try again!",E="Please enter your search query image";function l(s){p.show({message:s,messageColor:"#ffffff",backgroundColor:"#fe5549",progressBar:!1,position:"center"})}x.addEventListener("click",s=>{if(s.preventDefault(),!c.value){l(E);return}S(),q(),$(c.value).then(e=>{e.hits?(T(),v(e.hits)):l(P)}).catch(e=>console.log(e))});
//# sourceMappingURL=index.js.map
